# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=10, verbose_name='文章分类')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('comment_response', models.TextField(verbose_name='评论回复')),
                ('comment_like', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.Article')),
            ],
            options={
                'ordering': ('comment_time',),
                'verbose_name_plural': '评论管理',
            },
        ),
    ]
