# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_categroy_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categroy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blog.Categroy', verbose_name='分类'),
            preserve_default=False,
        ),
    ]
