# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_article_categroy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, help_text='可选，如若为空将摘取正文的前54个字符', max_length=7, null=True, verbose_name='摘要'),
        ),
    ]
