# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20170420_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Article', verbose_name='文章评论'),
        ),
    ]
