# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20170423_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_body',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
