# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20170519_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, through='Blog.Membership', to='Blog.Tag', verbose_name='标签集合'),
        ),
        migrations.AddField(
            model_name='membership',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Article'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Tag'),
        ),
    ]
