# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20170521_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='article',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='tag',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Blog.Tag', verbose_name='标签集合'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
